# LibraryBuild.yml
# Github workflow script to test compile all examples of an Arduino library repository.
#
# Copyright (C) 2021  Armin Joachimsmeyer
# https://github.com/ArminJo/Github-Actions

# This is the name of the workflow, visible on GitHub UI.
name: LibraryBuild

on:
  workflow_dispatch: # To run it manually
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - '**LibraryBuild.yml'
    - '**library.properties'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
  build:
    name: ${{ matrix.arduino-boards-fqbn }} - test compiling examples

    runs-on: ubuntu-latest # I picked Ubuntu to use shell scripts.

    strategy:
      matrix:
        arduino-boards-fqbn:
          - arduino:avr:uno
          - arduino:avr:leonardo
          - arduino:avr:mega
          - digistump:avr:digispark-tiny:clock=clock1
          - digistump:avr:digispark-pro
          - ATTinyCore:avr:attinyx5:chip=85,clock=1internal
          - megaTinyCore:megaavr:atxy6o:chip=1616,clocko=16internal,millis=timerd,bodvoltage=4v2,bodmode=disabled,resetpinopti=UPDI,entrycond=default,startuptimeopti=8,bootloaderuart=default,optimization=size,iremode=mors,printf=default,attach=allenabled

        # Choose the right platform for the boards we want to test. (maybe in the future Arduino will automatically do this for you)
        # With sketches-exclude you may exclude specific examples for a board. Use a comma separated list.
        #############################################################################################################
        include:
          - arduino-boards-fqbn: digistump:avr:digispark-tiny:clock=clock1  # ATtiny85 board @1 MHz
            platform-url: https://raw.githubusercontent.com/ArminJo/DigistumpArduino/master/package_digistump_index.json

          - arduino-boards-fqbn: digistump:avr:digispark-pro
            platform-url: https://raw.githubusercontent.com/ArminJo/DigistumpArduino/master/package_digistump_index.json

          - arduino-boards-fqbn: ATTinyCore:avr:attinyx5:chip=85,clock=1internal
            platform-url: http://drazzy.com/package_drazzy.com_index.json
          
          - arduino-boards-fqbn: megaTinyCore:megaavr:atxy6o:chip=1616,clocko=16internal,millis=timerd,bodvoltage=4v2,bodmode=disabled,resetpinopti=UPDI,entrycond=default,startuptimeopti=8,bootloaderuart=default,optimization=size,iremode=mors,printf=default,attach=allenabled
            platform-url: http://drazzy.com/package_drazzy.com_index.json

      # Do not cancel all jobs / architectures if one job fails
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          platform-url: ${{ matrix.platform-url }}
          build-properties: ${{ toJson(matrix.build-properties) }}
